<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\EccomersAPI.Database\EccomersAPI.Database.csproj" />
    <ProjectReference Include="..\EcomersAPI.DataAbstraction\EccomersAPI.DataAbstraction.csproj" />
    <ProjectReference Include="..\EcommersAPI.Domain\EcommersAPI.Domain.csproj" />
  </ItemGroup>

</Project>
