<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="MediatR" Version="13.0.0" />
    <PackageReference Include="MediatR.Extensions.Autofac.DependencyInjection" Version="13.0.0" />
    <PackageReference Include="MongoDB.Driver" Version="3.4.2" />
    <PackageReference Include="MongoDB.Driver.Core" Version="2.30.0" />
    <PackageReference Include="Swashbuckle.AspNetCore" Version="6.6.2" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\EccomersAPI.BusinessLogics\EccomersAPI.BusinessLogics.csproj" />
    <ProjectReference Include="..\EccomersAPI.CommonDomain\EccomersAPI.CommonDomain.csproj" />
    <ProjectReference Include="..\EccomersAPI.Database\EccomersAPI.Database.csproj" />
    <ProjectReference Include="..\EccomersAPI.Repositories\EccomersAPI.Repositories.csproj" />
    <ProjectReference Include="..\EcommersAPI.Domain\EcommersAPI.Domain.csproj" />
  </ItemGroup>

</Project>
